---
- name: Restart server
  sudo: yes
  command: shutdown -r now "Ansible triggered a server restart"
  async: 0
  poll: 0
  ignore_errors: true
  tags: restart

- name: Waiting for server to come back
  sudo: no
  local_action: wait_for host={{ inventory_hostname }} state=started
  tags: restart
