---
- name: Install nginx
  sudo: yes
  apt: name=nginx
  tags: nginx

- name: Save original default server config
  sudo: yes
  command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.orginal creates=/etc/nginx/sites-available/default.orginal
  tags: nginx

- name: Setup HHVM FastCGI
  sudo: yes
  template: src=default dest=/etc/nginx/sites-available/
  tags: nginx

- name: Start nginx
  sudo: yes
  service: name=nginx state=restarted
  tags: nginx
